name: CI - Blue/Green failover test

on:
  push:
    branches: [ main, master ]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    env:
      # Default values for testing - override with repository secrets in production
      BLUE_IMAGE: httpd:2.4-alpine  # Default test image that responds to healthz
      GREEN_IMAGE: httpd:2.4-alpine
      ACTIVE_POOL: blue
      RELEASE_ID_BLUE: blue-test-release
      RELEASE_ID_GREEN: green-test-release
      PORT: 80
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env for docker-compose
        run: |
          # Use secrets if available, otherwise fall back to default env values
          cat > .env <<EOF
          BLUE_IMAGE=${BLUE_IMAGE}
          GREEN_IMAGE=${GREEN_IMAGE}
          ACTIVE_POOL=${ACTIVE_POOL}
          RELEASE_ID_BLUE=${RELEASE_ID_BLUE}
          RELEASE_ID_GREEN=${RELEASE_ID_GREEN}
          PORT=${PORT}
          EOF

      - name: Start docker-compose
        run: |
          docker compose up -d --wait

      - name: Wait for services
        run: |
          sleep 8

      - name: Run failover verification (PowerShell)
        shell: pwsh
        run: |
          pwsh -File ./test/verify.ps1

      - name: Tear down
        if: always()
        run: |
          docker compose down -v
